// Section I - English Language (Q1-30). English only, per bilingual-paper convention.
module.exports = {
  title: 'SECTION I — ENGLISH LANGUAGE',
  titleHi: 'खण्ड I — अंग्रेजी भाषा',
  meta: 'Q. 1 to 30  |  30 Marks',
  items: [
    { dir: true, en: 'Directions (Q. 1–10): Read the following passage carefully and answer the questions given below it. Certain words are printed in bold to help you locate them while answering some of the questions.' },
    { passage: [
      "India's push towards financial inclusion has undergone a quiet transformation over the past decade. When the Pradhan Mantri Jan Dhan Yojana was launched in 2014, the immediate goal was simple: give every household a bank account. Millions of accounts were opened within months, and the scheme was widely celebrated as a statistical triumph. Yet critics were quick to point out that a large proportion of these accounts remained **DORMANT**, holding zero balance and seeing no transactions. Opening an account, they argued, is not the same as using one.",
      "What changed the picture was not another account-opening drive but the arrival of cheap data and the Unified Payments Interface. Once a villager could send money to a relative in another state from a basic smartphone, without paying a fee and without visiting a branch, the account stopped being a piece of paper and became a tool. Transaction volumes climbed steeply, and dormancy rates fell. The lesson was instructive: infrastructure alone does not create habits; utility does.",
      "However, the transformation remains **UNEVEN**. Regions with weak network coverage continue to depend on business correspondents, who travel with hand-held devices to serve customers who cannot reach a branch. These correspondents are the human face of the system, but they are thinly paid and inadequately supervised, and instances of overcharging are not rare. Moreover, the growing sophistication of digital fraud has begun to erode the confidence of precisely those users who were the last to be included. A single fraudulent debit can push a first-time user back to keeping cash at home.",
      "The task before policymakers, therefore, is no longer to count accounts. It is to ensure that the least experienced user is also the best protected."
    ]},
    { n:1, en:'What was the principal criticism of the Jan Dhan Yojana mentioned in the passage?',
      o:['It failed to open a sufficient number of accounts','A large share of the accounts opened under it stayed inactive','It was launched without adequate government funding','It deliberately excluded rural households','It was confined to urban areas alone'], ans:1,
      sol:'Para 1: critics pointed out that a large proportion of the accounts "remained dormant, holding zero balance and seeing no transactions."' },
    { n:2, en:'According to the passage, what genuinely increased the actual usage of bank accounts?',
      o:['A second, larger account-opening drive','Higher rates of interest offered on deposits','The arrival of cheap data together with UPI','The recruitment of more business correspondents','Sustained government advertising campaigns'], ans:2,
      sol:'Para 2 states the change came from "the arrival of cheap data and the Unified Payments Interface."' },
    { n:3, en:'What does the author mean by the phrase "the account stopped being a piece of paper and became a tool"?',
      o:['Paper passbooks were formally discontinued','The account began serving a practical, everyday purpose','All accounts were converted into digital wallets','Banks ceased issuing printed statements','The account was used only to receive subsidies'], ans:1,
      sol:'The contrast is between a dormant, merely documentary account and one actively used — i.e. it acquired real utility.' },
    { n:4, en:'Which of the following is stated in the passage as a problem concerning business correspondents?',
      o:['They refuse to travel to remote villages','They are overpaid relative to the work they do','They are thinly paid and inadequately supervised','They have no access to hand-held devices','They operate only in large urban centres'], ans:2,
      sol:'Para 3: "they are thinly paid and inadequately supervised, and instances of overcharging are not rare."' },
    { n:5, en:'Why is digital fraud described as being particularly damaging?',
      o:['It causes very large losses to the banks','It principally targets wealthy customers','It erodes the confidence of the newly included users','It slows down overall transaction speeds','It raises the retail cost of mobile data'], ans:2,
      sol:'Para 3: fraud erodes "the confidence of precisely those users who were the last to be included."' },
    { n:6, en:'According to the author, what should now be the focus of policymakers?',
      o:['Counting the number of accounts opened','Expanding the physical branch network','Protecting the least experienced users','Further reducing the cost of mobile data','Replacing business correspondents with ATMs'], ans:2,
      sol:'Final para: ensure "that the least experienced user is also the best protected."' },
    { n:7, en:'"Infrastructure alone does not create habits; utility does." This statement suggests that:',
      o:['Infrastructure is altogether unnecessary','People adopt a system when it is genuinely useful to them','Habits can be formed only through formal training','Utility companies ought to be permitted to run banks','Banking infrastructure should be privatised'], ans:1,
      sol:'The sentence contrasts mere availability with usefulness; adoption follows usefulness.' },
    { n:8, en:'Choose the word most nearly the SAME in meaning as **DORMANT** as used in the passage.',
      o:['Overdrawn','Inactive','Fraudulent','Joint','Recent'], ans:1,
      sol:'Dormant accounts are those with no transactions — i.e. inactive.' },
    { n:9, en:'Choose the word most OPPOSITE in meaning to **UNEVEN** as used in the passage.',
      o:['Rough','Partial','Uniform','Sudden','Visible'], ans:2,
      sol:'Uneven (inconsistent across regions) is opposed by uniform.' },
    { n:10, en:'Which of the following can be inferred from the passage?',
      o:['The Jan Dhan Yojana was an outright failure','Digital fraud has been eliminated from rural areas','Access to banking and meaningful use of banking are two different things','Business correspondents will shortly become unnecessary','Network coverage is now uniform across the country'], ans:2,
      sol:'The whole passage turns on the gap between opening an account (access) and using it (use).' },

    { dir: true, en: 'Directions (Q. 11–17): Each sentence below is divided into four parts, marked (a), (b), (c) and (d). Identify the part that contains an error. If the sentence has no error, mark (e) as your answer.' },
    { n:11, en:'The manager, along with his colleagues, (a) / were invited to the (b) / inauguration of the new branch (c) / near the railway station. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:1, noOpts:true,
      sol:'"along with his colleagues" is a parenthetical phrase; the subject remains the singular "The manager", so the verb must be "was invited".' },
    { n:12, en:'Hardly had he entered the hall (a) / than the audience (b) / stood up and began (c) / to applaud loudly. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:1, noOpts:true,
      sol:'"Hardly" is correlated with "when", not "than". ("No sooner … than", but "Hardly … when".)' },
    { n:13, en:'She is one of the most (a) / efficient officers who (b) / has ever worked (c) / in this department. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:2, noOpts:true,
      sol:'In "one of the + plural noun + who", the relative pronoun refers to the plural "officers"; hence "have ever worked".' },
    { n:14, en:'If I would have known (a) / about the strike, (b) / I would have postponed (c) / my journey. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:0, noOpts:true,
      sol:'The third conditional takes "If + had + past participle" in the if-clause: "If I had known".' },
    { n:15, en:'The committee have decided (a) / to defer the matter (b) / until the next meeting (c) / is convened. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:0, noOpts:true,
      sol:'Here the committee acts as a single body, so the singular verb is required: "The committee has decided".' },
    { n:16, en:'He was accompanied with (a) / his younger brother (b) / when he went to (c) / collect the certificate. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:0, noOpts:true,
      sol:'A person is accompanied BY another person; "accompanied with" is used of things.' },
    { n:17, en:'Neither the clerk nor the officers (a) / was present in the branch (b) / when the auditor (c) / arrived yesterday. (d) / No error (e)',
      o:['(a)','(b)','(c)','(d)','No error'], ans:1, noOpts:true,
      sol:'With "neither … nor", the verb agrees with the nearer subject — "officers" (plural) — so "were present".' },

    { dir: true, en: 'Directions (Q. 18–25): In the passage below there are blanks, each of which has been numbered. Against each number, five words are suggested, one of which fits the blank appropriately. Find the appropriate word in each case.' },
    { passage: [
      "Central banks across the world are re-examining the idea of issuing digital currency. The appeal is (18)______: a state-backed digital token would combine the convenience of private payment apps with the safety of sovereign money. Yet the design choices are far from (19)______. If citizens can hold such currency directly with the central bank, commercial banks may (20)______ deposits during periods of panic, weakening the very institutions that extend credit. To (21)______ this risk, several proposals cap individual holdings.",
      "Privacy is another (22)______ question. Cash is anonymous; a digital token need not be, and the state would in principle be able to (23)______ every transaction. Designers have therefore explored tiered systems in which small payments remain private while larger ones are (24)______. What is clear is that a digital currency is not merely a technical upgrade. It (25)______ decisions about the relationship between the citizen, the bank and the state."
    ]},
    { n:18, en:'', o:['obscure','obvious','reluctant','hostile','trivial'], ans:1, sol:'The colon introduces an explanation of why the idea is attractive — the appeal is obvious.' },
    { n:19, en:'', o:['settled','expensive','visible','recent','hidden'], ans:0, sol:'"Yet" signals contrast: the appeal is clear but the design choices are far from settled (i.e. still disputed).' },
    { n:20, en:'', o:['attract','generate','lose','insure','publish'], ans:2, sol:'A panic-driven shift of money to the central bank means commercial banks lose deposits — which explains "weakening".' },
    { n:21, en:'', o:['enlarge','ignore','welcome','contain','repeat'], ans:3, sol:'Caps on holdings are a measure to contain (limit) the risk just described.' },
    { n:22, en:'', o:['vexed','solved','cheerful','minor','absent'], ans:0, sol:'The paragraph goes on to describe a genuine dilemma, so the question is a vexed (difficult, contested) one.' },
    { n:23, en:'', o:['fund','trace','forgive','delay','waive'], ans:1, sol:'Contrasted with the anonymity of cash: a non-anonymous token lets the state trace transactions.' },
    { n:24, en:'', o:['forbidden','refunded','traceable','duplicated','untaxed'], ans:2, sol:'The tier contrast is private vs. traceable, echoing "trace" in the previous sentence.' },
    { n:25, en:'', o:['avoids','forces','postpones','conceals','reverses'], ans:1, sol:'"Not merely a technical upgrade" implies it compels — forces — deeper decisions.' },

    { dir: true, en: 'Directions (Q. 26–30): Each of the following sentences has two blanks. Choose the pair of words that fits both blanks most appropriately.' },
    { n:26, en:'The bank decided to ______ the loan application because the documents submitted were found to be ______.',
      o:['approve, genuine','reject, incomplete','forward, valid','accept, forged','delay, adequate'], ans:1,
      sol:'"because" demands a cause consistent with the action — incomplete documents justify rejection.' },
    { n:27, en:'Despite ______ warnings from the regulator, the company continued to ______ the norms.',
      o:['repeated, violate','rare, follow','gentle, obey','written, honour','strict, respect'], ans:0,
      sol:'"Despite" needs a contrast: warnings were repeated, yet the norms were still violated.' },
    { n:28, en:'The new branch manager was widely ______ for his ability to ______ disputes without escalating them.',
      o:['criticised, create','praised, settle','punished, resolve','known, worsen','blamed, avoid'], ans:1,
      sol:'"without escalating them" is positive, so the manager was praised for being able to settle disputes.' },
    { n:29, en:'Since the server remained ______ for several hours, customers were unable to ______ their transactions.',
      o:['active, complete','down, complete','busy, cancel','fast, delay','open, reverse'], ans:1,
      sol:'A server that is down for hours is the cause of customers being unable to complete transactions.' },
    { n:30, en:'The auditor’s report was so ______ that the board had no option but to ______ immediate action.',
      o:['vague, take','damning, initiate','mild, demand','brief, postpone','casual, order'], ans:1,
      sol:'"so … that … no option but to" needs a strong cause: a damning report forces the board to initiate action.' }
  ]
};
